- user:
    name: lincolnhack
    comment: deploy user
    group: nginx

- name: Set authorized key took from url
  authorized_key:
    user: lincolnhack
    state: present
    key: https://github.com/sdh100shaun.keys

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=NOPASSWD:/bin/systemctl start php72-php-fpm.service'
    validate: visudo -cf %s

- name: Add sudoers users to wheel group
  user: name={{item}} groups=wheel append=yes
  with_items: "{{ sudoers }}"
