- user:
    name: lincolnhack
    comment: deploy user
    group: nginx

- name: Set authorized key took from url
  authorized_key:
    user: lincolnhack
    state: present
    key: https://github.com/sdh100shaun.keys
