---
- name: install wget
  yum: name=wget state=present

- name: install openssl
  yum: name=openssl state=present

- name: Ensure that our ACME user exists
  user:
    name: "acme"
    createhome: no

- name: Setup our base SSL folder
  file:
    path: "/var/ssl"
    state: directory
    owner: "acme"
    group: nginx
    mode: 0750

- name: install curl
  yum: name=curl state=present

- name: install acme
  get_url:
    url: "https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh"
    dest: '/usr/local/bin/'
    mode: '0755'

- stat: "path=/etc/pki/tls/certs/{{domain.server_name}}.cer"
  register: st

- name: install cert
  shell: "acme.sh --issue -d {{domain.server_name}} -w /usr/share/nginx/html/ --force"
  when: (ansible_date_time.epoch|int - st.stat.mtime) > (1 * 60 * 60 * 24)

- name: generate dh params
  command: sudo openssl dhparam -out /etc/pki/tls/certs/dhparam.pem 4096 
  args: 
    creates: /etc/pki/tls/certs/dhparam.pem

- name: copy certs
  shell: "cp /root/.acme.sh/{{domain.server_name}}/*.cer /etc/pki/tls/certs"

- name: move keys
  shell: "cp /root/.acme.sh/{{domain.server_name}}/*.key /etc/pki/tls/private"

- name: check if conf file exists
  stat: 
    path: /etc/nginx/conf.d/{{domain.server_name}}.conf.off
  register: config_file

- name: move config
  shell: "mv /etc/nginx/conf.d/{{domain.server_name}}.conf.off /etc/nginx/conf.d/{{domain.server_name}}.conf"
  when: config_file.stat.exists == true

- name: restart nginx
  service: name=nginx state=restarted