- name: git install
  yum: name=git state=present

- name: set deploy keys
  shell: ssh-keygen -q -f /home/lincolnhack/.ssh/id_rsa -N "" &> /dev/null | echo 0

- name: set permissions
  file:
    path: /home/lincolnhack/.ssh/
    owner: lincolnhack
    recurse: yes

- name: Slurp hosts file
  slurp:
    src: /home/lincolnhack/.ssh/id_rsa.pub
  register: slurpfile

- name: add deploy key
  github_deploy_key:
    owner: "{{github_owner}}"
    repository: "{{github_repository}}"
    name: "lincolnhack-deploy"
    key: "{{ slurpfile['content'] | b64decode }}"
    token: "{{github_access_token}}"
    force: true
