---
- name: install nginx
  yum: name=nginx state=present


- name: Start the nginx service
  shell: systemctl start nginx

- name: Holding page
  template: src=index.tpl dest=/usr/share/nginx/html/index.html
