---
- name: install nginx
  yum: name=nginx state=present

- name: install ssl conf
  template: "src=conf.tpl dest=/etc/nginx/conf.d/{{domain.server_name}}.conf"

- name: Start the nginx service
  shell: systemctl start nginx

- name: ansible create directory example
  file:
    path: /usr/share/nginx/html/images
    state: directory

- name: Holding page
  template: src=index.tpl dest=/usr/share/nginx/html/index.html

- name: gzip config
  template: src=gzip.tpl dest=/etc/nginx/conf.d/gzip.conf
