---
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Add nginx repo 
  yum_repository:
    name: nginx
    description: nginx YUM repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: 0
    enabled: 1
    

- name: install nginx
  yum: 
   name: nginx
   state: present
  
- name: ansible create directory example
  file:
    path: /usr/share/nginx/html/images
    state: directory

- name: Holding page
  template: src=index.tpl dest=/usr/share/nginx/html/index.html

- name: gzip config
  template: src=gzip.tpl dest=/etc/nginx/conf.d/gzip.conf

- name: basic conf
  template: src=conf.basic.tpl dest=/etc/nginx/conf.d/default.conf

- name: check if conf file exists
  stat: 
    path: /etc/nginx/conf.d/{{domain.server_name}}.conf.off
  register: config_file

- name: create config
  template: src=conf.tpl dest=/etc/nginx/conf.d/{{domain.server_name}}.conf.off
  when: config_file.stat.exists == false

- name: restart nginx
  service: name=nginx state=restarted
